# Generated by Django 4.2.26 on 2025-11-11 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('noOfPersons', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='MenuTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('isComing', models.BooleanField(blank=True, null=True)),
                ('plusOne', models.BooleanField(default=False)),
                ('plusOneName', models.CharField(blank=True, max_length=100, null=True)),
                ('invite', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='response', to='invites.invites')),
                ('menuMain', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_main', to='invites.menutypes')),
                ('menuPlusOne', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_plusone', to='invites.menutypes')),
            ],
        ),
        migrations.CreateModel(
            name='Codes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('accessed', models.BooleanField(default=False)),
                ('lastAccess', models.DateTimeField(blank=True, null=True)),
                ('invite', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='code', to='invites.invites')),
            ],
        ),
    ]
