# Generated by Django 4.2.26 on 2025-11-11 14:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('date_last_access', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvitedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(blank=True, max_length=100, null=True)),
                ('given_name', models.CharField(blank=True, max_length=100, null=True)),
                ('invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='invites.invite')),
            ],
        ),
        migrations.CreateModel(
            name='MenuType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_coming', models.BooleanField(blank=True, null=True)),
                ('date_of_response', models.DateTimeField(default=django.utils.timezone.now)),
                ('invite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='invites.invite')),
            ],
        ),
        migrations.RemoveField(
            model_name='responses',
            name='invite',
        ),
        migrations.RemoveField(
            model_name='responses',
            name='menuMain',
        ),
        migrations.RemoveField(
            model_name='responses',
            name='menuPlusOne',
        ),
        migrations.DeleteModel(
            name='Codes',
        ),
        migrations.DeleteModel(
            name='Invites',
        ),
        migrations.DeleteModel(
            name='MenuTypes',
        ),
        migrations.DeleteModel(
            name='Responses',
        ),
        migrations.AddField(
            model_name='confirmedperson',
            name='invite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_people', to='invites.invite'),
        ),
        migrations.AddField(
            model_name='confirmedperson',
            name='menu_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_people', to='invites.menutype'),
        ),
    ]
