# Generated by Django 4.2.26 on 2025-11-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0002_confirmedperson_invite_invitedperson_menutype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='sent_invite',
            field=models.BooleanField(default=False),
        ),
    ]
