# Generated by Django 4.2.26 on 2025-11-11 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0003_invite_sent_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
